package com.hattonky.inventory.data.model;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a category in the inventory system.
 * This is a Room entity that maps to the "categories" table in the database.
 * Each category has an auto-generated ID and a name.
 */
@Entity(tableName = "categories")
public class Category {

    /**
     * The primary key for the category, auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;

    /**
     * The name of the category (e.g., Electronics, Furniture).
     */
    private String name;

    /**
     * Constructor to create a new Category object with the specified name.
     * The ID will be auto-generated when the entity is inserted into the database.
     *
     * @param name The name of the category.
     */
    public Category(String name) {
        this.name = name;
    }

    /**
     * Returns the ID of the category.
     *
     * @return The category's ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the ID of the category.
     * This is typically used by Room when the entity is saved in the database.
     *
     * @param id The ID to set.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the name of the category.
     *
     * @return The category name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the category.
     *
     * @param name The category name to set.
     */
    public void setName(String name) {
        this.name = name;
    }
}
