package com.hattonky.inventory.data.model;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents an item in the inventory system.
 * This is a Room entity that maps to the "items" table in the database.
 * Each item has an auto-generated ID, name, description, category, and an associated image path.
 */
@Entity(tableName = "items")
public class Item {

    /**
     * The primary key for the item, auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;  // Unique identifier for each item

    /**
     * The name of the item (e.g., Laptop, Chair).
     */
    private String name;

    /**
     * A description of the item providing more detail about its features or attributes.
     */
    private String description;

    /**
     * The category to which the item belongs (e.g., Electronics, Furniture).
     */
    private String category;

    /**
     * The path to the item's image file, stored locally.
     */
    private String imagePath;

    /**
     * Constructor to create a new Item object with the specified name, description, category, and image path.
     * The ID will be auto-generated when the entity is inserted into the database.
     *
     * @param name The name of the item.
     * @param description A brief description of the item.
     * @param category The category the item belongs to.
     * @param imagePath The file path to the item's image.
     */
    public Item(String name, String description, String category, String imagePath) {
        this.name = name;
        this.description = description;
        this.category = category;
        this.imagePath = imagePath;
    }

    /**
     * Returns the ID of the item.
     *
     * @return The item's ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the ID of the item.
     * This is typically used by Room when the entity is saved in the database.
     *
     * @param id The ID to set.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the name of the item.
     *
     * @return The item's name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the item.
     *
     * @param name The name to set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of the item.
     *
     * @return The item's description.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the item.
     *
     * @param description The description to set.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the category of the item.
     *
     * @return The item's category.
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the category of the item.
     *
     * @param category The category to set.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Returns the path to the item's image.
     *
     * @return The item's image path.
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Sets the path to the item's image.
     *
     * @param imagePath The image path to set.
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
}
